### ISSUE TITLE
[BUG] Unable to compile if UBL - MESH_BED_LEVELING is enabled

### ISSUE THREAD

**Issue by mrv96** [Desuuuu/Marlin#3]
As reported in the title, there is a compilation error if UBL is enabled. The error is:

![image](https://user-images.githubusercontent.com/13086678/99290454-9a7e8b80-283e-11eb-8e47-8fa23dd33c5e.png)

This happens because the method ExtUI::onMeshUpdate(signed char, signed char, ExtUI::probe_state_t) must be implemented.

I'm going to make a pull request that solves the issue.

**Comment by Desuuuu** [comment]
Fixed as of af52d99754f4c05827ab805b4e31431065dfe36e.

Thanks!
